id: I78801982
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T04:43:16+00:00'
last_modified: '2022-06-08T10:31:05.721124+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD90127
  title: འཛམ་ཐང་རྫོང་གི་ས་ཆའི་མིང་བཏུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2269':
      image_group_id: I1PD90149
      title: ''
      total_pages: 132
      order: 1
      base_file: 2269.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
