id: P009368
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD90127
  title: འཛམ་ཐང་རྫོང་གི་ས་ཆའི་མིང་བཏུས
  author: ''
  volumes:
    d9700a78efc1403b854a9de20f5fbe21:
      image_group_id: I1PD90149
      title: ''
      volume_number: 1
      total_pages: 132
