id: P009368
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:35:31.672670
source_metadata:
  id: bdr:W1PD90127
  title: འཛམ་ཐང་རྫོང་གི་ས་ཆའི་མིང་བཏུས
  author: ''
  volumes:
    d9700a78efc1403b854a9de20f5fbe21:
      image_group_id: I1PD90149
      title: ''
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
